# -*- coding: utf-8 -*-
"""17 Sustainable Development Goals, multilingual labels for the UI."""

SDG_NAMES = {
    "en": [
        "No Poverty",
        "Zero Hunger",
        "Good Health and Well-being",
        "Quality Education",
        "Gender Equality",
        "Clean Water and Sanitation",
        "Affordable and Clean Energy",
        "Decent Work and Economic Growth",
        "Industry, Innovation and Infrastructure",
        "Reduced Inequalities",
        "Sustainable Cities and Communities",
        "Responsible Consumption and Production",
        "Climate Action",
        "Life Below Water",
        "Life on Land",
        "Peace, Justice and Strong Institutions",
        "Partnerships for the Goals",
    ],
    "fr": [
        "Pas de pauvreté",
        "Faim « zéro »",
        "Bonne santé et bien-être",
        "Éducation de qualité",
        "Égalité entre les sexes",
        "Eau propre et assainissement",
        "Énergie propre et d'un coût abordable",
        "Travail décent et croissance économique",
        "Industrie, innovation et infrastructure",
        "Inégalités réduites",
        "Villes et communautés durables",
        "Consommation et production responsables",
        "Mesures relatives à la lutte contre les changements climatiques",
        "Vie aquatique",
        "Vie terrestre",
        "Paix, justice et institutions efficaces",
        "Partenariats pour la réalisation des objectifs",
    ],
    "es": [
        "Fin de la pobreza",
        "Hambre cero",
        "Salud y bienestar",
        "Educación de calidad",
        "Igualdad de género",
        "Agua limpia y saneamiento",
        "Energía asequible y no contaminante",
        "Trabajo decente y crecimiento económico",
        "Industria, innovación e infraestructura",
        "Reducción de las desigualdades",
        "Ciudades y comunidades sostenibles",
        "Producción y consumo responsables",
        "Acción por el clima",
        "Vida submarina",
        "Vida de ecosistemas terrestres",
        "Paz, justicia e instituciones sólidas",
        "Alianzas para lograr los objetivos",
    ],
}

DEFAULT_LANG = "en"
